### ISSUE TITLE
Not working for Timeline Source

### ISSUE THREAD

**Issue by Allinol-zz** [relrelb/CPPS-PCL#10]
![image](https://user-images.githubusercontent.com/41040164/42815914-17cd1da0-89f3-11e8-9442-0544f0c67966.png)
it makes this error when i use this with timeline source link:
http://github.com/Times-0/Timeline

**Comment by relrelb** [comment]
Thanks for reporting. This should be fixed per my [latest commit](https://github.com/relrelb/CPPS-PCL/commit/adad44444a57c8d41634a830e6a445eb52a0305b).
