### ISSUE TITLE
Follow command

### ISSUE THREAD

**Issue by n0faces** [relrelb/CPPS-PCL#12]
Not able to type in terminal when follow command is active. Unable to unfollow so i have to restart login.py

loving it tho thanks for sharing.

**Comment by relrelb** [comment]
Hello Cyrelix,
Thanks for using my program. This issue should be fixed now per my [latest commit](https://github.com/relrelb/CPPS-PCL/commit/a6861d26beb9b524b005aa18164d7b2e699902cc).
