### ISSUE TITLE
This isnt an issue 

### ISSUE THREAD

**Issue by n0faces** [relrelb/CPPS-PCL#13]
Would you be willing to tell me where i can edit the follow command so it doesnt clone when i choose to follow?

**Comment by relrelb** [comment]
Hi, assuming you want to prevent the follow command from changing clothes, you can comment [line `client.py:1280`](https://github.com/relrelb/CPPS-PCL/blob/master/client.py#L1280).

**Comment by n0faces** [comment]
thank you.
