### ISSUE TITLE
Opens up to Recaptcha and loads the cpr page but says the plugin not supported

### ISSUE THREAD

**Issue by Pokemates** [relrelb/CPPS-PCL#15]
I'm not sure if this has something to do with adobe flash player but i can play it normally on chrome and stuff just not using the login.py. Btw can you add club penguin universe?

**Comment by Pokemates** [comment]
![broken](https://user-images.githubusercontent.com/45781614/49782138-61436400-fd69-11e8-8d90-133a5aecb122.png)
this what it looks like

**Comment by relrelb** [comment]
Do you still encounter that problem? If so, what cefpython version do you have? This can be checked in the python interpreter by:
```python
>>> import cefpython3
>>> print cefpython3.__version__
```

**Comment by relrelb** [comment]
Please refer to [issue 22](https://github.com/relrelb/CPPS-PCL/issues/22), and make sure you are on the latest commit.
