### ISSUE TITLE
SetBounds() not implemented on this platform

### ISSUE THREAD

**Issue by ghost** [relrelb/CPPS-PCL#17]
For CPR, the captcha window opens even there's no captcha on it.
![image](https://user-images.githubusercontent.com/31494103/52184345-fa6d8480-27c6-11e9-848e-d37a95e2e0c7.png)

**Comment by relrelb** [comment]
Do you still encounter that problem? If so, what platform do you use and what cefpython version do you have? This can be checked in the python interpreter by:
```python
>>> import cefpython3
>>> print cefpython3.__version__
```

**Comment by relrelb** [comment]
Hey, thank you for letting me know about this issue. I have committed a fix for that error and it should not appear anymore on Windows.
