### ISSUE TITLE
Continued violation of our game rules

### ISSUE THREAD

**Issue by ncodex2** [relrelb/CPPS-PCL#2]
Hello,

I am writing to you to notify you that continued violation of the Club Penguin Rewritten rules will have your whole Internet Service Provider blocked, and we will write a letter to your current provider which is allowing this amount of dynamic IP addresses, and all of your IP addresses will be subjected to third party anti-spam services.

Per our Privacy Policy:

"In addition to the purposes described in Section 1, we may actively collect and use email addresses, messages sent by the child and user names to track usage and to ensure users are following the site’s Terms of Use. In addition, we may use an email address, IP address and user name to ban a user temporarily or permanently from the Club Penguin Rewritten website if that user engages in inappropriate conduct on the site. We also may use information in the aggregate to analyze site usage.
We may disclose information where we are required to do so by law, for example, in response to a court order or a subpoena, or where we disclose information to service providers or other group companies who provide support for the operations of our website and who do not use or disclose the information for any other purpose. To the extent permitted by applicable law, we also may disclose PII in response to a law enforcement agency’s or other public agency’s (including schools or children services) request or if we feel that such disclosure may prevent the instigation of a crime, facilitate an investigation related to public safety or protect the safety of a child using our website, protect the security or integrity of our website, or enable us to take precautions against liability.".

I would recommend stopping any activity and attacks on our servers before we get directly in contact with your Internet Service Provider & other third party spam services.

**Comment by AmusingThrone** [comment]
I am writing to you to bring to your attention that while CPR may be an educational instance (which is still illegal), it does not give you the correct status to threaten an ISP to shutdown it's clients connection. I suggest you review the rights you are entitled within the United States, as your site is based in the Netherlands, which holds no jurisdiction here.
