### ISSUE TITLE
script to generate list of penguins by ID

### ISSUE THREAD

**Issue by Emucr** [relrelb/CPPS-PCL#20]
is there a way to do this? for example get list of penguin names from ID 1-1000

**Comment by relrelb** [comment]
The following script should write to "penguins.txt" all penguin names with ID < 1000:

```python
from login import login

with login() as client:
	for penguin in xrange(1, 1000):
		with open("penguins.txt", "a") as file:
			file.write(client.get_penguin_name(penguin) + "\n")
```

However, some servers may not response, as they require to be a friend of the penguin whose name is requested to improve security.

Penguins that do not exist in the server would show as "penguin #_id_".
