### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by Emucr** [relrelb/CPPS-PCL#21]
Do you know what hashing algoritm oasis uses?

Is it MD5 with a salt if so whats the salt?

**Comment by missaustraliana** [comment]
Hmm I Am Not Sure, Maybe Do Some Research On The Topic.


Thanks,
Acid

**Comment by relrelb** [comment]
Oasis Penguin indeed uses a slightly different hasing algorithm, involving a special addition to the normal handshake protocol.
You can see its implementation in [`client.py`](https://github.com/relrelb/CPPS-PCL/blob/0caeb95133795a4946e44c4704716fc96151c7df/client.py#L293).
