### ISSUE TITLE
Free Penguin

### ISSUE THREAD

**Issue by Rayc22** [relrelb/CPPS-PCL#23]
Free penguin does not work

**Comment by djmuted** [comment]
That's because I've added a recaptcha to login procedure and no bots will work now, sorry for that.

**Comment by masterwhite54** [comment]
U are a monster

**Comment by djmuted** [comment]
> U are a monster 

I really have nothing against bots (that's how I was learning coding in the first place, by coding bots for Club Penguin), but they were abused and used in evil ways in Free Penguin and I had no choice but block them from accessing the game. I'd be grateful if FreePenguin was removed from CPPS-PCL supported server list, but if that won't be the case - I will continue on adding more security measures stopping the bots from logging in.

**Comment by relrelb** [comment]
I've fixed the support for Free Penguin in commit 77fb4574777de86411723956cd34fc8b4aa9bf30.
Now it passes the login process, but none of the commands work.
I'll take a look at it once I have time.

**Comment by Rayc22** [comment]
Okey, fine, I'm waiting for an answer.

**Comment by turicfr** [comment]
Closing since Free Penguin [shut down](https://freepenguinxyz.github.io/freepenguin/) in May. Dropped support in cd0abe7.
