### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by humboldt123** [relrelb/CPPS-PCL#24]
Whenever I run this with Python 2.6 I get this issue. I installed all the modules listed here but this seems to be an issue with `common.py`. 
```
File "C:\Users\John Doe\Desktop\pyth\common.py", line 73
indexed = {command._name: command for command in commands}
```

**Comment by relrelb** [comment]
Hi, thank you for letting me know.
Unfortunately, Python 2.6 isn't compatible with this project as dict comprehension was first introduced in Python 2.7. Try to install Python 2.7 and run it again.
