### ISSUE TITLE
Adding Cozy Penguin

### ISSUE THREAD

**Issue by noahball** [relrelb/CPPS-PCL#27]
Can you add Cozy Penguin (https://cozypenguin.net)
I'm the owner of it so if you need some information about the game engine DM me on Discord Alto#0517

**Comment by acidpancake** [comment]
@altoweb I have just seen cozy penguin. your puffle party is great but the lodge needs fixing. its the normal lodge not the puffle party lodge.
Also I Would Like A Position On Your Cpps.
Email Me At kohlhagentoby@gmail.com

**Comment by relrelb** [comment]
I've added support for Cozy Penguin in commit 2d5eab5b20c12b3eb07acf0c28bb5d345de54cb1.
However from some reason the server kicks me out after the login process finishes.
Do you have any idea why?

**Comment by noahball** [comment]
If you mean through the script, then it's most likely the fact that the client attempts sending information to nodejs and the play page with your penguin information.

**Comment by noahball** [comment]
Works fine for me.

**Comment by turicfr** [comment]
Closing since Cozy Penguin shut down. Dropped support in 9289a8d.
