### ISSUE TITLE
Add All

### ISSUE THREAD

**Issue by Emucr** [relrelb/CPPS-PCL#3]
Can you add an add all feature for CPR ITEMS

**Comment by relrelb** [comment]
This can be accomplished by writing a custom script. For example, to add all items with ID < 1000:
```python
from login import login
from client import ClientError

with login() as client:
	for item in xrange(1, 1000):
		try:
			client.add_item(item)
		except ClientError:
			pass
```

**Comment by lk1ra** [comment]
> This can be accomplished by writing a custom script. For example, to add all items with ID < 1000:
> 
> ```python
> from login import login
> from client import ClientError
> 
> with login() as client:
> 	for item in xrange(1, 1000):
> 		try:
> 			client.add_item(item)
> 		except ClientError:
> 			pass
> ```

where do we insert the script?
