### ISSUE TITLE
Cannot connect to CPO Server.

### ISSUE THREAD

**Issue by addiebart** [relrelb/CPPS-PCL#34]
python login.py -r yes cpo
Username: wakababy13
Server: sleet
Connecting to login server at mail.cponline.pw:3724...
Failed to connect to login server at mail.cponline.pw:3724
Failed to connect

I don't think mail.cponline.pw is correct. seems like a mail server.

**Comment by addiebart** [comment]
host should be 144.217.10.63

**Comment by relrelb** [comment]
Hello, thank you for notifying me this!

It seems that they changed the IP address of both login and game servers. I went ahead and added all of Club Penguin Online's new servers, so you should be able to login now per to the [latest commit](https://github.com/relrelb/CPPS-PCL/commit/f75d4332ed6fe0c20dbcfc1a0d6e538651a1b8c9).
