### ISSUE TITLE
Not working for CPR

### ISSUE THREAD

**Issue by apratimshukla6** [relrelb/CPPS-PCL#35]
Seems like CPR has patched this script and the commands give Error #800 for Game Cheat.

**Comment by bebdon** [comment]
yh true, multi may have been patched out too on CPO
![Screenshot_7](https://user-images.githubusercontent.com/61237851/81459293-182e5400-9197-11ea-876d-186e14bdf725.png)
![Screenshot_8](https://user-images.githubusercontent.com/61237851/81459294-1cf30800-9197-11ea-8306-28d6da28c566.png)

**Comment by turicfr** [comment]
Fixed by 0bd975c.
