### ISSUE TITLE
Error with 'walk' command in multi.py

### ISSUE THREAD

**Issue by Rencify** [relrelb/CPPS-PCL#4]
I login to a CPPS with four penguins in order to use the 'square' shape, but whenever I try to use the 'walk' command from the shell, it gives me this error:
`Traceback (most recent call last):
  File "multi.py", line 291, in <module>
    main()
  File "multi.py", line 278, in main
    msg = commands[command](clients, *params)
  File "multi.py", line 74, in walk
    for client, offset in zip(clients, shape["offsets"]):
NameError: global name 'shape' is not defined`

**Comment by relrelb** [comment]
Hey, thanks for notifying. This should be fixed per to the [last commit](https://github.com/relrelb/CPPS-PCL/commit/49f42504d0336c627ba5f1fd0b87e9df1b398fa3).
