### ISSUE TITLE
CPPS-PCL may be archived.

### ISSUE THREAD

**Issue by missaustraliana** [relrelb/CPPS-PCL#41]
Hey everyone!

I'm thinking from the last update to this repo that this project may be archived over the CPPS drama. Most CPPSes have already patched this program anyway so this repo is just history now...

Waddle On.

**Comment by turicfr** [comment]
There isn't really a reason to archive this repo, in my opinion.

While most supported CPPSes are down/patched, this can still work on newer CPPSes that use popular servers (e.g. [houdini](https://github.com/solero/houdini), [kitsune](https://github.com/widd/kitsune), [Auroris](https://github.com/HagridHD/Auroris)). 

I know this repo isn't massively maintained these days, but pull requests are always welcome. Also, from time to time I try to update some servers.
