### ISSUE TITLE
can't follow someone

### ISSUE THREAD

**Issue by ghost** [relrelb/CPPS-PCL#6]
it would error when to follow someone pls fix this ASAP

**Comment by relrelb** [comment]
Can you please provide more information such as CPPS, screenshot, so it would be easier to detect and resolve?

**Comment by ghost** [comment]
CPU https://cdn.discordapp.com/attachments/432138167122919427/437066506896146437/unknown.png

**Comment by relrelb** [comment]
Seems like that link is not public. Please fix it and maybe supply more information like exception traceback and what commands did you perform before getting to the error.

**Comment by ghost** [comment]
oops sorry please wait
