### ISSUE TITLE
Add Club Penguin Rewritten

### ISSUE THREAD

**Issue by ghost** [relrelb/CPPS-PCL#7]
i got issues while connecting to CPR  here is the screenshot 
![image](https://user-images.githubusercontent.com/36565252/39917918-29f0b774-5539-11e8-8bb4-1b35ddcd945c.png)

**Comment by relrelb** [comment]
This should work now per the [latest commit](https://github.com/relrelb/CPPS-PCL/commit/f5ab9e6f55020727fa8c69d42949faca7be1fa19).
