### ISSUE TITLE
error using multi.py

### ISSUE THREAD

**Issue by ghost** [relrelb/CPPS-PCL#8]
this is the error message 
![image](https://user-images.githubusercontent.com/36565252/39928567-e9b72c84-555f-11e8-939e-0001ec95bd8d.png)

**Comment by ghost** [comment]
its in CPR

**Comment by relrelb** [comment]
Hey, thanks for issuing that. This should work now per the [latest commit](https://github.com/relrelb/CPPS-PCL/commit/df602c5fb912011bc509ecd3d5762d3b86ca7218).
