### ISSUE TITLE
error while following with Login.py

### ISSUE THREAD

**Issue by ghost** [relrelb/CPPS-PCL#9]
![image](https://user-images.githubusercontent.com/36565252/40263428-53727d18-5b3c-11e8-8061-5ef154cfc271.png)
   CPPS:CPR 
Windows:8.1
Python:2.7

**Comment by relrelb** [comment]
Good to know, this should work now per the [latest commit](https://github.com/relrelb/CPPS-PCL/commit/c97293537de5311843b7846b42c909a429d4582e).
